worldapi:
  build: .
  links:
    - db

db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: 123456secret
    MYSQL_DATABASE: homestead 
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
